### ISSUE TITLE
Bad funcion name is triggering JuantAldea's OCD

### ISSUE THREAD

**Issue by MrManlu** [JuantAldea/NES#1]
In line:
https://github.com/JuantAldea/NES/blob/master/include/cpu.h#L126

"address_..." should be changed to "addressing_..."

**Comment by JuantAldea** [comment]
Hello! address_accumulator was declared but actually not even defined.
Instructions:
* [ASL A](https://www.pagetable.com/c64ref/6502/?tab=2#ASL)
* [LSR A](https://www.pagetable.com/c64ref/6502/?tab=2#LSR)
* [ROL A](https://www.pagetable.com/c64ref/6502/?tab=2#ROL)
* [ROR A](https://www.pagetable.com/c64ref/6502/?tab=2#ROR)
Are the only instructions that use Accumulator Addressing, but they don't have Implied Addressing variants, so Accumulator addressing can be handled as Implied.

Thanks!
